version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
  - copyloopvar
  - dupl
  - errcheck
  - errorlint
  - exptostd
  - goconst
  - gocritic
  - gocyclo
  - gosec
  - govet
  - ineffassign
  - lll
  - misspell
  - modernize
  - nakedret
  - nilerr
  - perfsprint
  - prealloc
  - revive
  - staticcheck
  - testifylint
  - unconvert
  - unparam
  - unused
  - usetesting
  settings:
    revive:
      rules:
      - name: comment-spacings
  exclusions:
    generated: lax
    rules:
    - linters:
      - lll
      path: api/*
    - linters:
      - dupl
      - lll
      path: internal/*
    - linters:
      - gosec
      path: e2e/*
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gofmt
  - goimports
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
