---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.siutsin.com
  resources:
  - servicewatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.siutsin.com
  resources:
  - servicewatchers/finalizers
  verbs:
  - update
- apiGroups:
  - core.siutsin.com
  resources:
  - servicewatchers/status
  verbs:
  - get
  - patch
  - update
