# This rule is not used by the project k3s-apiserver-loadbalancer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the core.siutsin.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k3s-apiserver-loadbalancer
    app.kubernetes.io/managed-by: kustomize
  name: servicewatcher-editor-role
rules:
- apiGroups:
  - core.siutsin.com
  resources:
  - servicewatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.siutsin.com
  resources:
  - servicewatchers/status
  verbs:
  - get
