# This rule is not used by the project k3s-apiserver-loadbalancer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.siutsin.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k3s-apiserver-loadbalancer
    app.kubernetes.io/managed-by: kustomize
  name: servicewatcher-viewer-role
rules:
- apiGroups:
  - core.siutsin.com
  resources:
  - servicewatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.siutsin.com
  resources:
  - servicewatchers/status
  verbs:
  - get
