name: Delete Untagged Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: ghcr.io cleanup action
        uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1
        with:
          delete-untagged: true
          delete-ghost-images: true
          older-than: 3 months
          keep-n-tagged: 10
